### ISSUE TITLE
Issue with broken links

### ISSUE THREAD

**Issue by raphaelsalomao3** [samuelcolvin/watchgod#15]
Hi,

I was just testing Watchgod as an alternative to Watchdog when I ran into this bug which I'm not sure if it's intended behaviour, but I find important to report. 

The program returns an error whenever it comes across broken links:
`error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/tmp/.com.google.Chrome.NdlWPj/SingletonCookie'`

Apparently, it gets stuck and stops processing newer changes. Also the CPU goes sky high when it's happening.

Steps to reproduce:

1. Create test file
    $ touch /tmp/test
2. Create symbolic link to test file on desired folder:
    $ ln -s /tmp/test /opt/testfile
3. Remove original file
    $ rm /tmp/test
4. Run sample code on /opt

**Comment by vanyakosmos** [comment]
I wasn't able to reproduce. What python version did you use? I tried 3.5 and 3.7.
Even switching back to `tags/v0.0.3` didn't help me to reproduce this error.

**Comment by raphaelsalomao3** [comment]
Hey - sorry but I don't remember what I was using or what for :D 

You can close this issue.

**Comment by kernc** [comment]
Got this error, specifically:
```
error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/etc/alternatives/builtins.7.gz'
error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/etc/alternatives/builtins.7.gz'
error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/etc/alternatives/builtins.7.gz'
error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/etc/alternatives/builtins.7.gz'
...
```
while running a docker container that specifies (an equivalent of):
```dockerfile
ENTRYPOINT ["uvicorn", "app:app", "--reload"]
```
`--reload` was, obviously, the troubling part.

**Comment by allen-munsch** [comment]
@kernc i just ran into this issue as well. Any idea how to get it working with `--reload` ?
