### ISSUE TITLE
Depend on Rust's Notify 'crate'

### ISSUE THREAD

**Issue by paul-hammant** [samuelcolvin/watchgod#25]
https://github.com/passcod/notify

^ Yup, another team's work in a heavy lifting language. 

Ruby, Java (etc) folks should also depend on notify then we get decent effort to performance tune and bugfix **once** and bind to more elegant HLLs like Python **multiple times**. The alternative is to code it yourself and end up with Watchdog's 137 open issues and 20 unconsumed pull requests.

**Comment by samuelcolvin** [comment]
Sounds good to me, but I'm currently not clear about python's interface with rust. Is it production ready?

If you'd like to work in it that would be great. Otherwise I'll look when I get a chance.

**Comment by graingert** [comment]
> Is it production ready?

there's a nice setuptools plugin that works like cython https://github.com/PyO3/setuptools-rust
