### ISSUE TITLE
RegExpWatcher

### ISSUE THREAD

**Issue by mozesa** [samuelcolvin/watchgod#31]
Dear **Samuel** **Colvin,**

I am writing to you to ask for your kind help regarding your awesome watchgod.

What I want is to use the „watch” with a "RegExpWatcher" watcher.

```
for changes in watch('./path/to/dir'):
    print(changes)
```

The problem that I have not managed to use the RegExpWatcher.

I tried the `watcher_cls=watchgod.RegExpWatcher` argument, but it did not help.

Another thing, yesterday when I was monitoring a directory with watchgod, I noticed that it suddenly began to report all the files being in that certain directory. _But those files were not modificated, created, copied, etc during the monitoring time._ It was strange, so I decided, that I set up another filter concerning the reported file modification datetime.

Here you can see the snippet.

```
def generate_filenames(path):

    for changes in watchgod.watch(path=path):
        for status, location in changes:
            if (
                status == watchgod.Change.added
                and len(pathlib.Path(location).stem) == 14
                and "WD" in pathlib.Path(location).stem
                and datetime.datetime.now()
                - datetime.datetime.fromtimestamp(
                    pathlib.Path(location).stat().st_mtime
                )
                >= datetime.timedelta(seconds=3600)
            ):
                yield location
```

Would you be so kind as to give me the right direction.

I really appreciate your kind help.

Best Regards,

**Comment by samuelcolvin** [comment]
Hi, thanks for the question.

Regarding `RegExpWatcher`, it seems to be working fine for me, here's an example that matches any file ending `.txt`:

```py
from watchgod import watch, RegExpWatcher

for changes in watch('./tests', watcher_cls=RegExpWatcher, watcher_kwargs=dict(re_files=r'.*\.txt', re_dirs='.*')):
    for status, location in changes:
        print(status, location)
```

Unfortunately, the `re_files` and `re_dirs` arguments are both required which they shouldn't be, but other than that it's all working.

> Another thing, yesterday when I was monitoring a directory with watchgod, I noticed that it suddenly began to report all the files being in that certain directory. But those files were not modificated, created, copied, etc during the monitoring time.

I haven't seen this before, if you get the issue again and can explain it please create an issue with OS details etc.
