### ISSUE TITLE
Reports old files

### ISSUE THREAD

**Issue by mozesa** [samuelcolvin/watchgod#35]
Dear **Samuel**,

I am writing to you because of an issue I mentioned previously.
What I have been bumped into is that watchgod reports old files wich aren't modified during the "monitoring time".

It happens when the connection to a remote (network) folder is lost, but after that it is reconnected. Afterwards it has happened, it begins to report all the files being in that certain directory.

The os is win7.

How could I help? What information do you need?

What is your advice?

Best Regard,

P.S.: the network was wireless one.

**Comment by mozesa** [comment]
Another piece of information that the network was wireless.

**Comment by samuelcolvin** [comment]
Afraid I don't know, watchgod wasn't designed or tested on remote connections.

I suspect the real problem would be to use inotify and friends via #25.
