### ISSUE TITLE
I want print(filename) if a file added in directory using WatchGod.

### ISSUE THREAD

**Issue by bemoregt** [samuelcolvin/watchgod#36]
Hi, @samuelcolvin @pyup-bot 

I want print(filename) if a file added in directory using WatchGod.

Like this -

if Change.status == added : 
    print(Changes.filename) 

How can I coding this ?

Thanks in advance ~

Best,
@bemoregt.

**Comment by samuelcolvin** [comment]
Not much point in asking a bot for help :-)

```py
import asyncio

from watchgod import Change, awatch


async def main():
    async for changes in awatch('tests'):
        for change_type, path in changes:
            if change_type == Change.added:
                print(path)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by bemoregt** [comment]
@samuelcolvin 

Thanks a lot .

I'll try that.
