### ISSUE TITLE
watchgod foobar.main

### ISSUE THREAD

**Issue by pahaz** [samuelcolvin/watchgod#39]
I just try to run example form docs.

1. create foobar.py file with aiohttp code

2. run watchgod

```
$ watchgod foobar.main
ImportError: No module named 'foobar'
```

https://github.com/samuelcolvin/watchgod#cli

**Comment by samuelcolvin** [comment]
Sorry about the slow reply here, somehow this slipped through the net (I guess via the look at it on your phone while drunk, ponder, forget hole).

This should be fixed via #43, would be great if you could try that and let me know if it fixes your problem.
