### ISSUE TITLE
watchgod CLI doesn't forward signals to its child process

### ISSUE THREAD

**Issue by elatt** [samuelcolvin/watchgod#41]
This is most noticeable when running the `watchgod` CLI command as part of a docker-compose setup to run an `aiohttp` app. Even if you set `stop_signal: SIGINT` on your container, the container will fail to shut-down properly and result in sending a `SIGKILL` to halt your App. You can work around this by using `tini` or some other init system to send the signal to the process group.

**Comment by samuelcolvin** [comment]
This is because the terminal (at least on Linux) will send SIGINT to subprocesses as well as the main process.

PR welcome, or you could just implement your own script and do the forwarding.

**Comment by jmfederico** [comment]
Related to #46
