### ISSUE TITLE
[FEATURE] add ‘closed’ as change type

### ISSUE THREAD

**Issue by mr-bjerre** [samuelcolvin/watchgod#56]
I have a server for file uploads. With low latency I need to trigger some python code that reads the incoming files and...

I have an issue right now though. Some times the files are empty and I think it’s because the upload is not done yet. How can I determine if the file is done being written to?

I think inotify have this functionality but I agree with you that it is nice to have it platform independent. 

Do you have a proposal for on how to handle this?

**Comment by samuelcolvin** [comment]
I think you'd need to add you're own logic to either:
* see if the file is still open somehw
* poll the file to see if it's size has stopped changing.
