### ISSUE TITLE
[Question] How to integrate with external apps like celery

### ISSUE THREAD

**Issue by pySilver** [samuelcolvin/watchgod#59]
Hi!

Thanks for an alternative for watchdog! What is the proper way to make it work with things like celery?

Normally celery starts this way: `celery -A config.celery_app worker -l INFO` 
so my guess was: `watchgod celery --args -A config.celery_app worker -l INFO` or `watchgod /opt/venv/bin/celery --args -A config.celery_app worker -l INFO` since celery itself is just a python file:

```
#!/opt/venv/bin/python
# -*- coding: utf-8 -*-
import re
import sys

from celery.__main__ import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

But it fails with:

```"/opt/venv/bin/celery" doesn't look like a module path```

**Comment by samuelcolvin** [comment]
Sorry for the slow response.

Not enough information here to help much I'm afraid.

**Comment by emilecaron** [comment]
Answer:
`watchgod celery.__main__.main --args -A config.celery_app worker -l INFO`

**Comment by nbraun-wolf** [comment]
I like @emilecaron 's answer better but you can also write a small function to start celery in worker mode and invoke it with watchgod.

tasks.py

```python
celery_app = Celery(__name__)

def run():
   celery_app.start(argv=["worker", "-l", "info" ])
```

Then

```bash
watchgod tasks.run
```

I haven't figured out how to pass works with the `--args` flag though. The start method is supposed to use sys.args if no argv was provided but it doesnt seem those are progpagated in a functional way.

**Comment by hyzyla** [comment]
In case if you are looking for solution in 2022:
```shell
watchfiles "celery  -A config.celery_app worker -l INFO" src
```
