### ISSUE TITLE
[Question]How to monitor 2 or more directories? 

### ISSUE THREAD

**Issue by flashlxy** [samuelcolvin/watchgod#61]
How to monitor 2 or more directories? I use a multi-process way to call a single directory monitoring, I feel this implementation is not very elegant, is there a more elegant way to achieve it? Has anyone achieved it? Thank you! The following is part of my multi-process code:
    ...

    `def loop_watcher(self, directory):
        self.loop = asyncio.get_event_loop()
        print("add_signal_handler.")
        signal.signal(signal.SIGINT, self.raise_graceful_exit)
        signal.signal(signal.SIGTERM, self.raise_graceful_exit)
        print(" Ctrl+C 停止运行.")
        print(f"pid {os.getpid()}: 发送 SIGINT 和 SIGTERM 信号退出循环")
        try:
            self.loop.run_until_complete(self.watching(directory))
        except GracefulExit:
            pass
        finally:
            if self.loop is not None:
                self.loop.close()  
    def main(self):
        pool = Pool(processes=len(self.paths), initializer=self.init_worker)
        for directory in self.paths:
            if os.path.isdir(directory):
                pool.apply_async(self.loop_watcher, (directory, ))
        try:
            print("Waiting forever.")
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            print("Caught KeyboardInterrupt, terminating workers")
            pool.terminate()
            pool.join()
            sys.exit(1)
        else:
            print("Quitting normally")
            pool.close()
            pool.join()`

...

**Comment by samuelcolvin** [comment]
Please format your code so it can be read.

This shouldn't be too hard, but I haven't done it.

**Comment by flashlxy** [comment]
> Please format your code so it can be read.
> 
> This shouldn't be too hard, but I haven't done it.

Now almost formatted, thanks.

**Comment by samuelcolvin** [comment]
You don't need multiple processes, you can monitor multiple directories in the same event loop.

**Comment by flashlxy** [comment]
> You don't need multiple processes, you can monitor multiple directories in the same event loop.

Thank you very much for your answers, but still don't understand, can you provide a simple example?

**Comment by flashlxy** [comment]
> You don't need multiple processes, you can monitor multiple directories in the same event loop.

- Found a solution through your prompt, thank you very much. There is much to learn in asynchronous programming. The solution is roughly as follows:

```Python
async def watcher(self, directories):    
       await asyncio.gather(*[self.watching(directory) for directory in directories])
```

**Comment by samuelcolvin** [comment]
Great, something like that should work well.

**Comment by samuelcolvin** [comment]
I needed this too.

Here's a working implementation of watching multiple directories without any changes to watchgod:

```py
import asyncio
from watchgod import awatch


async def watch_multiple(*paths):
    watchers = [awatch(p) for p in paths]
    while True:
        done, pending = await asyncio.wait([w.__anext__() for w in watchers], return_when=asyncio.FIRST_COMPLETED)
        for t in pending:
            t.cancel()
        for t in done:
            yield t.result()


async def main():
    async for changes in watch_multiple('dir1', 'dir2'):
        print(changes)


if __name__ == '__main__':
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
```

**Comment by NightMachinary** [comment]
Since the pending coroutines are canceled, can't some changes be missed? 

> I needed this too.
> 
> Here's a working implementation of watching multiple directories without any changes to watchgod:
> 
> ```python
> import asyncio
> from watchgod import awatch
> 
> 
> async def watch_multiple(*paths):
>     watchers = [awatch(p) for p in paths]
>     while True:
>         done, pending = await asyncio.wait([w.__anext__() for w in watchers], return_when=asyncio.FIRST_COMPLETED)
>         for t in pending:
>             t.cancel()
>         for t in done:
>             yield t.result()
> 
> 
> async def main():
>     async for changes in watch_multiple('dir1', 'dir2'):
>         print(changes)
> 
> 
> if __name__ == '__main__':
>     try:
>         asyncio.run(main())
>     except KeyboardInterrupt:
>         pass
> ```
