### ISSUE TITLE
A bug when monitoring the network mapping disk.

### ISSUE THREAD

**Issue by flashlxy** [samuelcolvin/watchgod#62]
Hi

- I tested the program written with the watchgod package on the win server 2012r2, and found that when monitoring the network mapped disk, when manually disconnecting the network mapped disk, watchgod will monitor the deletion change that does not actually exist, when reconnecting the network  When the disk is mapped, it will generate additional changes to all files in the monitored directory. These false changes will cause unintended actions.  Is this reasonable?  Thank you!

The result is shown below:

![image](https://user-images.githubusercontent.com/3060134/82218327-532a4780-994e-11ea-95c2-1443389b8901.png)

**Comment by samuelcolvin** [comment]
I think fixing this is outside the bounds of what watchgod does.
