### ISSUE TITLE
How can I define the polling rate?

### ISSUE THREAD

**Issue by fkromer** [samuelcolvin/watchgod#69]
To me it's not clear how [`awatch`](https://github.com/samuelcolvin/watchgod/blob/master/watchgod/main.py#L49) exactly works. Let's say I'd like to watch a single file with a polling period of 200ms. How do I have to call `awatch`?

**Comment by berland** [comment]
Use the keywordargument `normal_sleep=5000` for a 5 sec poll-time:
```
>>> from watchgod import  watch
>>> for changes in watch("/tmp", normal_sleep=5000):
...     print(changes)
```

**Comment by fkromer** [comment]
Thanks!
