### ISSUE TITLE
Ignore Emacs autosave files or more generally some pattern

### ISSUE THREAD

**Issue by rocky** [samuelcolvin/watchgod#71]
I think I'll like this package.

One problem I had using is that Emacs autosave files are detected. These files start with `.#`

I worked around this problem by changing the PythonWatcher like this:

```python
class PythonWatcher(DefaultDirWatcher):
    def should_watch_file(self, entry):
        return entry.name.endswith(('.py', '.pyx', '.pyd')) and not entry.name.startswith(".#")
```

Of course there should be a more general way to do something like this.

Thanks for providing this package.

**Comment by samuelcolvin** [comment]
fixed by #70
