### ISSUE TITLE
mkdir not captured

### ISSUE THREAD

**Issue by berland** [samuelcolvin/watchgod#72]
I struggled a bit with different Watchers to detect the creation of directories, but failed to get it to work.

I understood eventually that I had to also add a file to the newly created directory before an event was emitted. Is this intentional (if so, it might be relevant for the documentation)?

**Comment by samuelcolvin** [comment]
Well I wrote it to look for files when they change, so directory changes aren't considered.

Happy to accept a PR to improve the documentation.
