### ISSUE TITLE
doesnt seem to work on osx

### ISSUE THREAD

**Issue by maddanio** [samuelcolvin/watchgod#78]
Hi, I just tried a simple test (from the pypy example: https://pypi.org/project/watchdog/). and on osx it kinda bahaves strange. so I run it on a non existing file:
`python3 test_watchdog.py test`
then I update that file by moving another file over it:
`touch test2 && mv test2 test`
and I want to be able to do that multiple times. thing is on the first chagne I get this event:
```
2021-04-07 09:23:24 - queue_event <DirDeletedEvent: event_type=deleted, src_path='/Users/daniel/Documents/git/game-on-server/python/tests/test', is_directory=True>
2021-04-07 09:23:24 - Deleted directory: /Users/daniel/Documents/git/game-on-server/python/tests/test
```
whis is wrong, and then after subsequent updates I get no events at all.
can watchdog only watch directories?

**Comment by maddanio** [comment]
ah, ok, it seems so, if I watch the directory instead I actually get the updates I need, but also many more. also I dont really want to watch a whole directory. so its not possible to watch a file?

**Comment by oprypin** [comment]
Your report is about a completely unrelated project. So I would ask to close this.

**Comment by samuelcolvin** [comment]
@oprypin - good spot.

**Comment by maddanio** [comment]
Oops :)
