### ISSUE TITLE
test_awatch_log is flaky

### ISSUE THREAD

**Issue by Newbytee** [samuelcolvin/watchgod#84]
The `test_awatch_log` is flaky and fails on slow systems and/or systems under heavy load. I can reproduce it by running two games (Krunker and SuperTuxKart) while simultaneously running the test on my laptop. What happens is that the number of messages containing "DEBUG" goes below 4 and the test thus fails.

You might wonder if this really is a problem - after all, you don't usually run multiple games while testing your code. The problem is that while packaging watchgod for Alpine Linux I experienced this test randomly failing on their continuous integration (CI) on certain arches (armhf, aarch64, s390x), presumably as a result of me not being the only person who uses these CI runners and the systems thus being under heavy load.

I don't have a proposed way to fix this, and I understand if it's something you don't want to fix, but I thought I would report it nonetheless.

**Comment by samuelcolvin** [comment]
I'll need more details on what's going wrong to fix this.
