### ISSUE TITLE
`watchgod` blocking Flask API server in SSE

### ISSUE THREAD

**Issue by ricardo-reis-1970** [samuelcolvin/watchgod#89]
# Context
I have an eventstream on Vue to feed with SSE information from a small XML file whenever it changes. My backend is a Flask app, although I'm upgrading it to FastAPI.

I have a `watchdog` solution that uses its standard `observer.start()`, which is a thread. This allows me to run concurrently. I'm trying to replace `watchdog` with `watchgod`.

The `watchgod` solution is `async` coroutines, which seem to be using `ThreadPoolExecutor`. Here's what I'm trying to do:
## `handler()`
This is the function that is supposed to be looking nfor changes:
```python
async def handler():
    file = os.path.join(path, xml_file)
    async for changes in awatch(path, watcher_cls=RegExpWatcher, watcher_kwargs={'re_files': re_files}):
        change = changes.pop()[0]
        if change.name in ('added', 'modified'):
            patient_data = ET.parse(file)
            patient_dict = parse_patient(patient_data)
            patient_id = registration_controller.save_patient(**patient_dict)
            patient_data = fix_patient_id(patient_data, patient_id)
            patient_data.write(vx_xml_file, encoding='UTF-8', xml_declaration=True, short_empty_elements=False)
            patient_dict['birth_date'] = patient_dict.pop('birthday')
            patient_queue.append(patient_dict)
```

## Endpoint
This is the function that is holding the SSE eventstream:
```python
app.route("/auto_register")
def emr_xml():
    def eventStream():
        while True:
            time.sleep(1)
            if patient_queue != []:
                patient_dict = patient_queue.pop()
                yield f"data: {json.dumps(patient_dict)}\n\n"
            else:
                yield 'retry: 1000\n\n'

    resp = Response(eventStream(), mimetype="text/event-stream")
    resp.headers["Access-Control-Allow-Origin"] = "*"
    resp.headers["Cache-Control"] = "no-cache"
    return resp
```
As you can see, I need to regularly "push forward" the connection by feeding it the `retry` bit, so I can't use either `async for changes in awatch` or `for changes in watch`, otherwise it will block until something changes in the file and I might timeout the SSE connection. In order to decouple this, I have the handler feeding a queue (which is just a `list`) and the endpoint checking it asynchronously every second.

# Kick-off
My issue is with starting the watcher. All the examples mention either doing it synch or starting the async version with:
```python
loop = asyncio.get_event_loop()
loop.run_until_complete(handler())
```
I also tried:
```python
asyncio.run(handler())
```
The effect is always the same: it will block my endpoint and, in fact, the whole application.

# What I can't do
I don't think I can go on and async thw whole thing. Flask won't work with that. I thought of having the `eventStream` function doing the `await asyncio.gather(handler(), reset())` where `reset` would just `await asyncio.sleep(1)` 1 second and return the `retry` string, but this also did not work.

# What I can do
Please tell me.

**Comment by samuelcolvin** [comment]
I'm going to close this as I suspect it's more related to starlette SSE, also this library has been completely rewritten in #98 so I doubt the same problem still exists.

Please create a new issue or comment here if you still have trouble.
