### ISSUE TITLE
Exiting and reloading on error

### ISSUE THREAD

**Issue by scottix** [samuelcolvin/watchgod#93]
Could we have a way to reload when it encounters an error?

The problem is, I am doing development in a container, if I save something with an error it will crash out and I have to restart the container.

![Selection_999(159)](https://user-images.githubusercontent.com/435727/147885084-46c0840c-13ba-41a1-81eb-3ed5a9e0fc9f.png)

Ideally it would be nice to reload and even have an option on number second to wait for the reload on error.

**Comment by samuelcolvin** [comment]
fixed by #98
